[samples]

[samples.mc]
key = "mc"
exposure_type = "pot"
trees = ['selected']
precompute = {reco_muon_ke_scaled='reco_leading_muon_ke/1000.0', true_muon_ke_scaled='true_leading_muon_ke/1000.0'}

[samples.mc_selected_systematics]
key = "mc"
exposure_type = "pot"
trees = ['selected']
systematics = ['selected_multisimTree', 'selected_multisigmaTree']

[samples.mc_signal_systematics]
key = "mc"
exposure_type = "pot"
trees = ['signal']
systematics = ['signal_multisimTree','signal_multisigmaTree']  

[samples.mc_nonmatched]
key = "mc"
exposure_type = "pot"
trees = ['selected_nonmatched']

[samples.mc_nu_cos]
key = "mc"
exposure_type = "pot"
trees = ['selected_nu', 'selected_cos']

[samples.mc_nu_only]
key = "mc"
exposure_type = "pot"
trees = ['selected_nu']

[samples.mc_cos_only]
key = "mc"
exposure_type = "pot"
trees = ['selected_cos']

[samples.mc_muonbump]
key = "mc"
exposure_type = "pot"
trees = ['selected_muonbump']

[samples.mc_outside_muonbump]
key = "mc"
exposure_type = "pot"
trees = ['selected_outside_muonbump']

[samples.mc_small_opening_angle]
key = "mc"
exposure_type = "pot"
trees = ['selected_small_opening_angle']

[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selected']

[samples.onbeam_muonbump]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selected_muonbump']

[samples.onbeam_outside_muonbump]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selected_outside_muonbump']

[samples.onbeam_small_opening_angle]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selected_small_opening_angle']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = -10
trees = ['selected']

[samples.offbeam_muonbump]
key = "offbeam"
exposure_type = "livetime"
override_category = -10
trees = ['selected_muonbump']

[samples.offbeam_outside_muonbump]
key = "offbeam"
exposure_type = "livetime"
override_category = -10
trees = ['selected_outside_muonbump']

[samples.offbeam_small_opening_angle]
key = "offbeam"
exposure_type = "livetime"
override_category = -10
trees = ['selected_small_opening_angle']

[samples.signal]
key = "mc"
exposure_type = "pot"
trees = ['signal']

[samples.intime]
key = "intime"
exposure_type = "livetime"
trees = ['offbeam']


